// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srojmtywgdlnzllgzynj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyb2ptdHl3Z2RsbnpsbGd6eW5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NzI4MjIsImV4cCI6MjA2MDQ0ODgyMn0.-79IeIoskTTdMcRg1CBjtX5OdXxCg-A6Vm1OvJqk2ak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);